### ISSUE TITLE
Input file is not a required parameter

### ISSUE THREAD

**Issue by jonyt** [corballis/sox-wrapper-java#2]
On this [line](https://github.com/corballis/sox-wrapper-java/blob/master/src/main/java/ie/corballis/sox/Sox.java#L101) you check for the input file parameter being set, but it's not a mandatory argument. For example, if you're recording audio it wouldn't be necessary.

**Comment by sawo** [comment]
What solution do you recommend? Simply drop the if statement?

**Comment by jonyt** [comment]
Yep.
